language: java

sudo: required

services:
 - docker
 
before_install:
 - docker build -t greendock .
 
script:
 - docker run greendock sh -c "ant; ant test;"

after_failure:
 - print_surefire_reports.sh
